import React from 'react';
import './App.css';
import {createStore} from 'redux';
import {connect, Provider} from 'react-redux';

/**
 * Stores keep track of state as JSON objects
 * 
 * State is generated by a reducer function
 * 
 * */
const reducer = () => (
  {message:"Hello world from Redux!"}
  )

const store = createStore(reducer);

const HelloComponent = ({helloProperty}) => 
  <h1>{helloProperty}</h1>

const HelloContainer = connect(
  state => ({helloProperty:state.message})
  )(HelloComponent)


function App() {
  return (
    <Provider store={store}>
      <div className="App">
        {/* <HelloComponent helloProperty="Hi, this is from Redux"/> */}
        <HelloContainer/>
      </div>
    </Provider>
  );
}

export default App;
